### ISSUE TITLE
Using s_gd2 for metric MDS

### ISSUE THREAD

**Issue by scottgigante** [jxz12/s_gd2#1]
Hi, I'm interested in trying out your code for metric MDS but I'm not quite sure how to use it. Could you please give an example of how I could use your framework in this context? Here's how I would do it with scikit-learn.

```
from sklearn.datasets import load_digits
from sklearn.manifold import MDS
from scipy.spatial.distance import pdist, squareform
X, _ = load_digits(return_X_y=True)
D = squareform(pdist(X))
embedding = MDS(n_components=2, dissimilarity='precomputed')
X_mds = embedding.fit_transform(D)
```

**Comment by jxz12** [comment]
Hi Scott, thank you for your question! I am away at a conference at the moment (although I think I have seen you around too? If so, let's meet!) and so will get back to you this evening with some example code. The function you'll want to use is s_gd2.mds_direct(), which directly takes your squareform() result as input. But it requires that you also give it a list of step sizes for the gradient descent, so I'll get back to you about how to compute that, or you can find it in the paper.

Jonathan

**Comment by jxz12** [comment]
Hi Scott, you can directly use the result of `pdist(X)` rather than the squareformed version. I have also updated the code to remove a bug and automate the setup size, so that you can simply use

```python3
D = pdist(X)
W = [1/(d*d) for d in D]
X_mds = s_gd2.mds_direct(X.shape[0], D, W)
```

Please install the latest version using pip if you have issues, and please let me know if there are any other problems!

**Comment by scottgigante** [comment]
Hi Jonathan,

Thanks very much for the explanation. Unfortunately I am not very good at checking emails during conferences -- maybe next time!

Thanks for this, I'll give it a go.

Scott

**Comment by scottgigante** [comment]
An update : s_gd2 gives a good starting point, but with default parameters doesn't get quite far enough on its own. I tried combining it with SMACOF as a fine tuning step, but surprisingly it actually took longer to fine tune than Classic MDS even though it provided a better empirical initialization.

![image](https://user-images.githubusercontent.com/8499679/67805609-a8ad0e80-fa67-11e9-8eac-6bdd72ff5789.png)

Code below if anyone is interested.

<details>

```
from sklearn.datasets import load_digits
from sklearn.manifold import MDS, smacof
from scipy.spatial.distance import pdist, squareform
import numpy as np
import s_gd2
import phate
import tasklogger

X, labels = load_digits(return_X_y=True)

def stress(X_mds, D):
    return ((pdist(X_mds) - D) ** 2).sum()

D = pdist(X)
D_sq = squareform(D)

tasklogger.log_start("s_gd2")
W = 1 / D**2
X_mds_sgd2 = s_gd2.mds_direct(X.shape[0], D, W)
sgd2_time = tasklogger.log_complete("s_gd2")
sgd2_stress = stress(X_mds_sgd2, D)

tasklogger.log_start("classic")
X_mds_classic = phate.mds.cmdscale_fast(D_sq, 2)
classic_time = tasklogger.log_complete("classic")
classic_stress = stress(X_mds_classic, D)

tasklogger.log_start("smacof")
X_mds_smacof = MDS(n_components=2, dissimilarity='precomputed').fit_transform(D_sq)
smacof_time = tasklogger.log_complete("smacof")
smacof_stress = stress(X_mds_smacof, D)

tasklogger.log_start("classic MDS + smacof")
X_init = phate.mds.cmdscale_fast(D_sq, 2)
X_mds_classic_smacof, _ = smacof(D_sq, init=X_init, n_init=1)
classic_smacof_time = tasklogger.log_complete("classic MDS + smacof")
classic_smacof_stress = stress(X_mds_classic_smacof, D)

tasklogger.log_start("s_gd2 + smacof")
X_init = s_gd2.mds_direct(X.shape[0], D, W)
X_mds_sgd2_smacof, _ = smacof(D_sq, init=X_init, n_init=1)
sgd2_smacof_time = tasklogger.log_complete("s_gd2 + smacof")
sgd2_smacof_stress = stress(X_mds_sgd2_smacof, D)

import scprep
import matplotlib.pyplot as plt

fig, (ax1, ax2, ax3, ax4, ax5) = plt.subplots(1, 5, figsize=(25, 4))
scprep.plot.scatter2d(X_mds_sgd2, c=labels, ax=ax1, legend=False, ticks=False,
                      title="s_gd2:\nt={:.1f}, stress={:.3g}".format(sgd2_time, sgd2_stress))
scprep.plot.scatter2d(X_mds_classic, c=labels, ax=ax2, legend=False, ticks=False,
                      title="classic:\nt={:.1f}, stress={:.3g}".format(classic_time, classic_stress))
scprep.plot.scatter2d(X_mds_smacof, c=labels, ax=ax3, legend=False, ticks=False,
                      title="smacof:\nt={:.1f}, stress={:.3g}".format(smacof_time, smacof_stress))
scprep.plot.scatter2d(X_mds_classic_smacof, c=labels, ax=ax4, legend=False, ticks=False,
                      title="classic + smacof:\nt={:.1f}, stress={:.3g}".format(classic_smacof_time, classic_smacof_stress))
scprep.plot.scatter2d(X_mds_combined, c=labels, ax=ax5, legend_anchor=(1,1), ticks=False,
                      title="s_gd2 + smacof:\nt={:.1f}, stress={:.3g}".format(sgd2_smacof_time, sgd2_smacof_stress))
fig.tight_layout()
fig.show()
```

</details>

**Comment by jxz12** [comment]
Hi Scott,

Thank you for your interest and for performing such thorough experiments. I had a look, and have found why SGD doesn't give a good result: I gave you code that is optimising a different error function! This is because of the line `W = 1 / D**2`, as normal MDS does not apply the w_ij factor to each term, and so W should just be full of ones. I also found that this change in weighting required slightly different step sizes to converge well, equivalent to setting epsilon=0.01 and t_max=30 from Section 2.1.1 of the paper. The following code should give the correct result:

```python3
W = np.ones(len(D)) 
t_max = 30
eps = 0.01
eta_max = 1/min(W) # this is silly because W is full of ones, but I've left it in to match the paper
eta_min = eps/max(W)
lambd = np.log(eta_max/eta_min) / (t_max-1)
etas = eta_max * np.exp(-lambd * np.arange(t_max))
X_mds_sgd2 = s_gd2.mds_direct(X.shape[0], D, W, etas)
```

![gigante](https://user-images.githubusercontent.com/13380149/67817248-f4f94e00-fa69-11e9-8f3a-d3b6d3e62e0f.png)

(note that SMACOF is still able to further improve the layout in this case because we did not use a fully convergent schedule like the one in the paper Section 2.1.2. The next release of the code will contain everything to make these options easy.)

**Comment by scottgigante** [comment]
Fantastic! I look forward to seeing the next release of the code -- it would be extremely useful for me if I could run `s_gd2` with this level of convergence without having to tune parameters.

**Comment by scottgigante** [comment]
Hi @jxz12 , any update on the status of this? I'm looking forward to integrating this into my codebase for a paper that will be published in a week or so, and wondering if there's any chance of it being available by then. At a minimum I would be very grateful if you could package a release of the code as it stands right now which would at least allow me to use s_gd2 as an initialization to SMACOF.

**Comment by jxz12** [comment]
Hi Scott, apologies for the delay - I've been preparing a submission for another conference and it's eaten up all my time! But thank you for the reminder because I needed a kick to do this, and will get a new version up by the end of this week (likely Saturday, hopefully that's not too late).

**Comment by scottgigante** [comment]
Thanks so much! Much appreciated.

**Comment by jxz12** [comment]
I have updated the code with a lot of improvements! The function mds_direct should now work with  simply a condensed distance matrix, where all other parameters are optional. In your code example it is simply `X_mds_sgd2 = s_gd2.mds_direct(X.shape[0], D)`. 

Random seeding now also gets passed to the C++ code, so setting the random_seed parameter results in the same output every time. Let me know if you have any issues with anything!

**Comment by scottgigante** [comment]
Ah unfortunately this latest update isn't working for me.

```
❯ pip install --user --upgrade s_gd2
Collecting s_gd2
  Downloading https://files.pythonhosted.org/packages/e8/7d/511f09944e01f3d31967dd6551f29132454f57172523356d371ecf959fdc/s_gd2-1.3.tar.gz (43kB)
     |████████████████████████████████| 51kB 2.5MB/s 
Requirement already satisfied, skipping upgrade: numpy in /usr/lib/python3.7/site-packages (from s_gd2) (1.16.3)
Requirement already satisfied, skipping upgrade: pycairo in /home/scottgigante/.local/lib/python3.7/site-packages (from s_gd2) (1.18.1)
Building wheels for collected packages: s-gd2
  Building wheel for s-gd2 (setup.py) ... done
  Stored in directory: /home/scottgigante/.cache/pip/wheels/14/8c/00/e8470490647fd96f9096dd6474a448d722b79ac900e4b7e786
Successfully built s-gd2
Installing collected packages: s-gd2
  Found existing installation: s-gd2 1.2
    Uninstalling s-gd2-1.2:
      Successfully uninstalled s-gd2-1.2
Successfully installed s-gd2-1.3

❯ python
Python 3.7.3 (default, Mar 26 2019, 21:43:19) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import s_gd2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scottgigante/.local/lib/python3.7/site-packages/s_gd2/__init__.py", line 1, in <module>
    from .s_gd2 import *
  File "/home/scottgigante/.local/lib/python3.7/site-packages/s_gd2/s_gd2.py", line 1, in <module>
    from .swig import layout as cpp
ModuleNotFoundError: No module named 's_gd2.swig'
```

**Comment by jxz12** [comment]
This is strange! It seems as if the sdist is packing things up nicely into the .tar.gz but for some reason the setup.py isn't putting the right things into site-packages. Eventually CI will solve this nicely, but I will fix this version for you ASAP.

**Comment by scottgigante** [comment]
Thanks so much!

**Comment by jxz12** [comment]
I presume you already worked out a way of installing it from your other suggestion on improving the build instructions, but I found that the issue was not including the s_gd2.swig package in the setup.py script. I will do some more tests and update the PyPI package tomorrow.

Thank you again for your help! And for bearing with me as I am not, as you probably have guessed, very experienced in the world of python packaging.

**Comment by scottgigante** [comment]
I did try, but initially had the same problem. Based on diagnosis I just fixed it by replacing `packages=['s_gd2']` with `packages=find_packages()`. Thanks!
