### ISSUE TITLE
Linux and Windows .whl releases

### ISSUE THREAD

**Issue by scottgigante** [jxz12/s_gd2#7]
Sorry to bombard you with issues. Would you consider releasing wheels for this project in future? Especially for Windows where building is more challenging. This can be done with CI to avoid having to build these manually.

**Comment by jxz12** [comment]
No problem at all, I am very grateful for your input. Wheels are a great idea that I will definitely include in the next release; I have never worked with CI before so there may be a delay, but it will definitely make my life easier.

**Comment by scottgigante** [comment]
I've transplanted some CI code that I've used previously to get a binary release of this on Windows, Linux and OS X. There are currently two issues preventing me from submitting a PR:

1. Travis CI is having an issue where the `deadsnakes` PPA is disallowed. I'm chasing this up here: https://travis-ci.community/t/bionic-doesnt-recognise-deadsnakes-on-apt-safelist/6228
2. `pycairo` is nontrivial to install in Windows. It seems to me that your `draw_png` function would be fairly simple to implement in `matplotlib` which is universally supported.

My feature branch is here: https://github.com/scottgigante/s_gd2/tree/sgdpy
and a temporary test release: https://pypi.org/project/sgdpy

**Comment by jxz12** [comment]
Wow, this is amazing that you can automate the production of all those wheels! Regarding pycairo, I already had some matplotlib code for drawing graphs somewhere in the repo, and so I'll add an extra `draw_matplotlib` function now. Do you know if it's possible to have python detect if the OS is Windows and disable the pycairo import if it is? I quite like that the `draw_png` function does the exact same as `draw_svg`, so it would be a shame to remove it completely.

**Comment by scottgigante** [comment]
Yes, I love CI :) Re: pycairo, one thing you could do is remove it from `install_requires` and then just raise a nice warning if someone tries to run `draw_png` without having it installed. e.g.

```
import warnings

try:
    ModuleNotFoundError
except NameError:
    # doesn't exist in py2.7
    ModuleNotFoundError = ImportError

def _draw_pycairo(...):
    import pycairo
    ...

def _draw_matplotlib(...):
    import matplotlib.pyplot as plt
    ...

def draw_png(..., backend=None):
    if backend is None or backend=='pycairo':
        try:
            import pycairo
        except ModuleNotFoundError:
            if backend == 'pycairo':
                # user explicitly asked for pycairo but it's not available
                warnings.warn("pycairo is not installed. Using `backend='matplotlib'` instead.", UserWarning)
            return draw_png(..., backend='matplotlib')
        else:
            return _draw_pycairo(...)
    elif backend == 'matplotlib':
        return _draw_matplotlib(...)
    else:
        raise ValueError("Expected `backend` in ['pycairo', 'matplotlib']. Got {}".format(backend))
```

**Comment by scottgigante** [comment]
And a further point: you can include `pycairo` in `extras_require={'plot':['pycairo']}` so that
```
pip install s_gd2
```
does not install pycairo but 
```
pip install s_gd2[plot]
```
does, if you so choose.

**Comment by jxz12** [comment]
Great! I have added the `draw_png()` functionality that you suggested, and so it should now have no dependency on pycairo unless the user already has it installed. Please let me know when you want to merge the CI fork and I will happily go ahead with it.

**Comment by scottgigante** [comment]
Sure, I'll open up the PR now. A couple of notes:
* you'll need to enable Travis CI and Appveyor in your github account
* you'll need to add your PyPi password as an environment variable in the Travis CI build
* you'll need to add an encrypted version of your PyPi password to `.appveyor.yml` with https://ci.appveyor.com/tools/encrypt
