### ISSUE TITLE
Instructions on building from source

### ISSUE THREAD

**Issue by scottgigante** [jxz12/s_gd2#8]
It would be great to include instructions on how to build from source in the README! Thanks!

**Comment by jxz12** [comment]
I agree! I did not make things easy - you have to move the layout.py and layout_wrap.cxx files from the SWIG folder into the base folder as it is, but I will edit MANIFEST.in so that you do not have to do that in the future at all.

**Comment by jxz12** [comment]
Instructions have been added to the README, and the structure has been redone to make everything smoother.

**Comment by scottgigante** [comment]
Thanks so much!

**Comment by scottgigante** [comment]
Just some feedback -- it might be easier to write this out in code rather than in English, e.g.

To install from source with precompiled C code:
```
git clone https://github.com/jxz12/s_gd2
cd s_gd2/cpp
python setup.py install
```
To install from scratch:
```
git clone https://github.com/jxz12/s_gd2
cd s_gd2/cpp/swig
swig -python -c++ layout.i
cd ..
python setup.py install
```

**Comment by jxz12** [comment]
Thank you, I will do this now!
